### ISSUE TITLE
Suggestion: Tooltip on Mouse Over

### ISSUE THREAD

**Issue by 01Lanz** [timhul/ClassicSim#132]
It would be nice to see the item stats on mouse over before actually selecting it.

As of now, we have to select the item and then go to the left (gear selected) in order to see what are the stats.

**Comment by timhul** [comment]
Fully agree, it's a technical limitation with ScrollView in QML which is why it isn't available. From what I've seen it requires a complete overhaul of the item selection view to get mouseover TTs to work.

I've wanted to do this forever, and in the past I even started the implementation once or twice but re-prioritized work to something more urgent.
