### ISSUE TITLE
Hunter Hitcap

### ISSUE THREAD

**Issue by Friedrich-Mocker** [timhul/ClassicSim#19]
From theory crafting we know that hitcap is key (9%). Going far beneath hitcap in classic sim as a hunter, e.g. replacing it with crit for instance, barely changes calculated dps.

Is there any way we can make sure hit is correctly calculated?

**Comment by Friedrich-Mocker** [comment]
All basic settings with "Loatheb" as encounter: 
![image](https://user-images.githubusercontent.com/19273717/66271953-12b90600-e864-11e9-9a95-ff7543dfec79.png)

calculates 307 DPS

same settings plus 3% hit
![image](https://user-images.githubusercontent.com/19273717/66271970-3a0fd300-e864-11e9-82ef-8116809befec.png)

calculates 308 dps

This cann NOT be correct

**Comment by timhul** [comment]
It does seem unreasonable, I will look into this.

**Comment by timhul** [comment]
Bug found that was introduced in 98617d29024341f9b904f884343738633d232ec6, reverted it and have now created a new release 19-10-07.

The bug incorrectly mixed 1 and 2-roll implementations which made the roll compare to an inconsistent range. If you check the statistics -> ability outcomes when adding hit you will see that as you add hit your crit chance decreases accordingly (and vice versa). That is why adding hit seemed to do nothing, it effectively reduced your crit chance as well.

This only affected hunters since they are the only users of the ranged attack table.
