### ISSUE TITLE
Why roll twice in magic attack table？

### ISSUE THREAD

**Issue by zl730** [timhul/ClassicSim#258]
I was reading the code of `MagicAttackTable.cpp`. But why it gives [a second roll](https://github.com/timhul/ClassicSim/blob/master/CombatRoll/AttackTables/MagicAttackTable.cpp#L17) after the hit?
```c
if(roll< crit_chance + miss_range)
    return MagicAttackResult::CRITICAL;
``` 
could be better i thought.

**Comment by f90** [comment]
I think it is because crit_chance is given as the fraction of HITS that end up in a crit. E.g. if you have 80% crit chance, crit_chance=0.8 so that the current code gives out a critical 80% of the time, IF it passed the hit check before. 

In this case your code would break since you have if(roll < 0.8 + miss_range), lets say miss is 0.2 (20% chance) then you would (if you don't miss) ALWAYS crit and never have a normal hit. But that would be 100% crit chance right?

**Comment by veluria** [comment]
Unlike melee crit, spell crit is a separate roll.

**Comment by kmmiles** [comment]
Spells are two roll as explained in the wiki under 'Mechanics Details'.

As an experiment try to find a caster sim/spreadsheet/calc that doesn't treat spells as two roll.

**Comment by f90** [comment]
To be fair you could decide between miss, hit and crit with just one random number between 0 and 1. 
If m is miss-ratio, c is crit ratio (numbers between 0 and 1), then you give out a miss if the random number is below m, a hit if its between m and m+c-cm, and crit otherwise.
E.g. miss of 20% (m=0.2), crit of 50% (c=0.5) => hit if random number is between 0.2 and 0.6, miss if lower, crit if higher.

**Comment by timhul** [comment]
> To be fair you could decide between miss, hit and crit with just one random number between 0 and 1.
> If m is miss-ratio, c is crit ratio (numbers between 0 and 1), then you give out a miss if the random number is below m, a hit if its between m and m+c-cm, and crit otherwise.
> E.g. miss of 20% (m=0.2), crit of 50% (c=0.5) => hit if random number is between 0.2 and 0.6, miss if lower, crit if higher.

This is true, but I think it is more clear to users expecting two-roll code and finding it does perform two rolls. The PRNG implementation is very fast so the cost of the extra roll is negligible.

Closing this as I think the sum of comments in this thread has provided sufficient background information.
