### ISSUE TITLE
Using Sulfuras crashes the application during sim

### ISSUE THREAD

**Issue by veluria** [timhul/ClassicSim#44]
Class and gear doesn't matter. During the sim, the application will crash if using Sulfuras. 

Crash is in `EnableBuffs.cpp`, line 98:

    buff->disable_buff();

**Comment by timhul** [comment]
The commit that introduced the bug was 188681c41fdf0e0dcdfa3b2613b23cab89dd8605 where the responsibility of disabling the marker buff moved from FireballInstant.cpp to, supposedly, the base class implementing periodic damage. This was not done properly.

Fixed in 7280cee6a9cab4d0aba982128bb2e1066c3b767e.
