### ISSUE TITLE
Addition of Tanking & Healing gear

### ISSUE THREAD

**Issue by WiiTee** [timhul/ClassicSim#53]
As much as I like to sim dps, sometimes it would be nice to be able to sim your damage as a tank or a healer for even more min-maxing, would it be possible to add these gear types to the gear already so that we can work towards a potential better setup than BIS lists say?
I've already found several BIS lists to be incorrect for DPS, so it would be nice.

Not just that, but actually adding all pieces of end-game gear for any class.
Currently you are not able to Simulate Spelladins 'cos you can't get any of the gear with spell power for them.

**Comment by timhul** [comment]
> As much as I like to sim dps, sometimes it would be nice to be able to sim your damage as a tank or a healer for even more min-maxing, would it be possible to add these gear types to the gear already so that we can work towards a potential better setup than BIS lists say?
> I've already found several BIS lists to be incorrect for DPS, so it would be nice.
>

+Defense, dodge, parry, armor, resistances are all supported.

+Healing is not available as a stat in the sim yet but you can still add them and the sim will just warn internally that it doesn't understand that stat until the backend supports it.

For tank damage it is important to start modelling damage taken from a boss as well since it has a major impact. This is part of the roadmap found [here](https://github.com/timhul/ClassicSim/wiki/Release-Roadmap).

> Not just that, but actually adding all pieces of end-game gear for any class.
> Currently you are not able to Simulate Spelladins 'cos you can't get any of the gear with spell power for them.

+Spell power is supported in the sim, but it is certainly possible spelladin pieces are mostly not attainable yet, I imagine those start to appear in P3 and forward.

As for the endgame gear in general I think most classes have a pretty decent coverage of items but it can still be improved.

I am closing this issue since I consider this issue to be a question that is now hopefully has an adequate answer. Feel free to open more issues if you have further questions or bugs / specific missing items.
