### ISSUE TITLE
+Fire and +Frost don't seem to modify mage spells

### ISSUE THREAD

**Issue by wafuso** [timhul/ClassicSim#70]
For example running a frost mage simulation with Elemental Mage Staff equipped gives the same results as with no weapon equipped. This seems to apply to all +frost or +fire gear.

**Comment by timhul** [comment]
Thanks for the report! The issue was not related to Frostbolt or any other spell. Instead it was a deeper issue when equipping items, wherein the school-specific spell damage bonuses were lost. This was not caught at unit test level for each individual spell since we don't do equips of items when setting up the test suite, we simply add directly to the power of the character. I have added specific tests for the copying of stats elements that will be extended in the future to make sure this does not happen to other stat types as well.

Fixed in 300cccc8aeac021be6459c2efe757ba14a031e09.

**Comment by timhul** [comment]
A new release has been created with this fix in it.

**Comment by wafuso** [comment]
Awesome!! thank you you so much for this tool and your response
