### ISSUE TITLE
Missing "Nature Damage" caused by "Thunderfury, Blessed Blade of the Windseeker" during simulation

### ISSUE THREAD

**Issue by jezecheng** [timhul/ClassicSim#83]
Hi there,

Am wondering if there's a missing or bug for the 1H sword weapon "Thunderfury, Blessed Blade of the Windseeker", when it's been selected and equipped it's not bringing any additional damage into "Breakdown" in "Statistics", and makes it even worse than "Brutality Blade".

BR
Tong

**Comment by timhul** [comment]
Hi, yes after a bit of investigating there was a bug introduced in 7a43cc4a456acb287b859646fbac7514b6102a21. It only affects Thunderfury since it is the only item to define two \<spell\> elements in the same \<proc\> element, only saving the last of the two (which is the Chain Lightning proc). Before said commit TF worked fine.

Fixed in be1206baee31319ab4845d0a9045977a3d267edb by reworking the \<spell\> element and removing \<source\> sub-element. Note that the sim still considers TF worse than Brutality Blade after the fix since the nature damage portion is subject to partial resistances (in the sim, this may still be a bug).

Thanks for the report!
