### ISSUE TITLE
[Rogue] Relentless Strikes and Ruthlessness bug

### ISSUE THREAD

**Issue by jluiken** [timhul/ClassicSim#89]
First of all: really enjoying the simulator; awesome job on the program so far and looking forward to expanding/improving its features!

As for this ticket: it appears that all ranks of rogue talents Relentless Strikes and Ruthlessness give a 100% chance to proc the accompanying effects.

This severaly overestimates the value of those talents, and allows for meme rotations like spam Eviscerating at one CP to deliver crazy DPS.

**Comment by jluiken** [comment]
Same issue with Seal Fate

**Comment by timhul** [comment]
Confirmed. There was an issue wherein the proc success was never checked for these two effects.

The way the implementation of these "special" proc effects (i.e. not from auto attacks or successful spell casts)  is that they can be triggered manually, but with that follows the responsibility of correctly checking the proc success. This should be changed so it is easier to not miss doing it, but the current way does allow for some easy testability, which a change to this area also has to facilitate. Further, there are not that many of these special proc effects which also reduce the impact of having to check the proc success manually.

Fixed in bc1d3940cc44e316fda4f95c96b6c5a1278161ac.
