### ISSUE TITLE
Rogue Hemorrhage not working

### ISSUE THREAD

**Issue by YAGjay** [timhul/ClassicSim#98]
Edit: There seems so be a general issue, since also for dagger rogues the sim appears to just use Sinister Strike (according to statistics). Talents & Rotation are properly set.

The rotation for hemorrhage seems to have issues detecting the Hemorrhage skill so it shows nothing in the rotation tab. Removing the prerequisite in the xml enables the rotation, but the simulation itself uses sinister strike still.

Although not so powerful right now, Hemorrhage builds for rogues can be pretty strong with more advanced equipment. Especially in later stages this competes with the "wasted" one debuff slot. Already right now it's interesting since in high equipped raids it's easier to keep up the pace also with a pve/pvp build of the people instead of pure pve builds.
Would be nice to compare how much/little you actually loose having a more joyful build like Hemo.

**Comment by timhul** [comment]
The Hemorrhage rotation contained an obsolete element which caused it to not be properly read. Fixed in 999d373bb6c1d8bbb0508ac766d93100067c79a4. With this commit selecting and running Hemorrhage rotation works fine.

As for Backstab there are no issues on my end when I make sure to actually click "Select rotation" for Combat Dagger, and not just browsing the rotation. Please make sure you both have a dagger equipped and a backstab rotation chosen.

I will close this issue as I consider the Hemorrhage part of it fixed in referenced commit. If you still have issues with Backstab please open a new issue.

Thanks for your report!
